### ISSUE TITLE
finalize sofer analysis

### ISSUE THREAD

**Issue by mcfrank** [StanfordPsych254/replication_project#13]
are we using the full model or the items analysis? check this!

**Comment by hawkrobe** [comment]
for posterity: we're using the by-subject analysis, which was a MANOVA. Note that the effect size we compute using the OSF specs differs by a factor of $sqrt{1/10}$ from the one Sofer et al report, since we correct for more predictors (it's the "explained variance by predictor" rather than the pure eta^2)
